spring:
  application:
    name: it7

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: sa
    password: 1

  liquibase:
    enabled: true
    default-schema: library

server:
  port: 8082
