spring:
  application:
    name: it7

  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

  liquibase:
    enabled: true
    default-schema: library

server:
  port: 8082
